/** @type {import('tailwindcss').Config} */
export default {
  content: ['./index.html', './src/**/*.{js,ts,jsx,tsx}'],
  darkMode: 'class',
  theme: {
    extend: {
      colors: {
        // MD3 Light tokens
        'primary': '#6a1cf6',
        'primary-dim': '#5d00e3',
        'primary-fixed': '#ac8eff',
        'primary-fixed-dim': '#a07dff',
        'primary-container': '#ac8eff',
        'on-primary': '#f7f0ff',
        'on-primary-container': '#2a0070',
        'on-primary-fixed': '#000000',
        'on-primary-fixed-variant': '#350088',
        'inverse-primary': '#9d79ff',
        'secondary': '#4953ac',
        'secondary-dim': '#3d469f',
        'secondary-fixed': '#cbceff',
        'secondary-fixed-dim': '#babfff',
        'secondary-container': '#cbceff',
        'on-secondary': '#f3f1ff',
        'on-secondary-container': '#343d96',
        'on-secondary-fixed': '#1f2882',
        'on-secondary-fixed-variant': '#3e47a0',
        'tertiary': '#006a28',
        'tertiary-dim': '#005d22',
        'tertiary-fixed': '#5cfd80',
        'tertiary-fixed-dim': '#4bee74',
        'tertiary-container': '#5cfd80',
        'on-tertiary': '#cfffce',
        'on-tertiary-container': '#005d22',
        'on-tertiary-fixed': '#004819',
        'on-tertiary-fixed-variant': '#006827',
        'error': '#b41340',
        'error-dim': '#a70138',
        'error-container': '#f74b6d',
        'on-error': '#ffefef',
        'on-error-container': '#510017',
        'surface': '#f5f6fb',
        'surface-dim': '#d1d4dc',
        'surface-bright': '#f5f6fb',
        'surface-variant': '#dadde4',
        'surface-tint': '#6a1cf6',
        'surface-container-lowest': '#ffffff',
        'surface-container-low': '#eff1f6',
        'surface-container': '#e6e8ee',
        'surface-container-high': '#e0e2e9',
        'surface-container-highest': '#dadde4',
        'on-surface': '#2c2f33',
        'on-surface-variant': '#595c60',
        'on-background': '#2c2f33',
        'background': '#f5f6fb',
        'outline': '#75777b',
        'outline-variant': '#abadb2',
        'inverse-surface': '#0c0e12',
        'inverse-on-surface': '#9b9da1',
      },
      fontFamily: {
        headline: ['Manrope', 'system-ui', 'sans-serif'],
        body: ['Inter', 'system-ui', 'sans-serif'],
        label: ['Inter', 'system-ui', 'sans-serif'],
        sans: ['Inter', 'system-ui', '-apple-system', 'sans-serif'],
      },
      borderRadius: {
        DEFAULT: '0.25rem',
        lg: '0.5rem',
        xl: '0.75rem',
        '2xl': '1rem',
        '3xl': '1.5rem',
        full: '9999px',
      },
    },
  },
  plugins: [],
}
